name: Bug Report
description: A generic bug report about vitest-codemod.
title: "[Bug?]: "
labels: ["bug", "triage"]

body:
  - type: checkboxes
    id: selfservice
    attributes:
      label: Self-service
      description: "Fixing bugs is always a great way to give back to open-source projects, and we're more than happy to answer questions and provide context."
      options:
        - label: "I'd be willing to implement a fix"

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is. A bug is **unintended**. A feature not being implemented is **not a bug**.
      placeholder: |
        eg: vitest-codemod crashes with a specific error.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: The _minimal_ steps to reproduce your issue.
      placeholder: |
        Please share code or minimal repo, and steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed behavior
      description: A clear and concise description of what happens.
      placeholder: |
        eg: The vitest-codemod script returned error with the following stack trace:
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you were expecting to happen.
      placeholder: |
        eg: The vitest-codemod script should have run successfully.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      render: shell
      description: |
        Run `vitest-codemod --version` and paste the result into the form
      placeholder: |
        vitest-codemod: 0.1.0
        - jscodeshift: 0.14.0
        - recast: 0.21.5
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. Or a screenshot if applicable.
