name: Bug Report (transform)
description: Bug report specific to a particular transform (like `jest`)
title: "[Bug?]: "
labels: ["bug", "triage"]

body:
  - type: checkboxes
    id: selfservice
    attributes:
      label: Self-service
      description: "Fixing bugs is always a great way to give back to open-source projects, and we're more than happy to answer questions and provide context."
      options:
        - label: "I'd be willing to implement a fix"

  - type: dropdown
    id: template-name
    attributes:
      label: Template name
      description: Which template are you seeing this error for?
      options:
        - jest
        - N/A (described above)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is. A bug is **unintended**. A feature not being implemented is **not a bug**.
      placeholder: |
        eg: Running transform "transformName" on the provided input causes it to crash.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Input code
      description: The _minimal_ input file to reproduce your issue.
      placeholder: |
        ```ts
        describe('Math', () => {
          test('.sqrt()', () => {
            expect(Math.sqrt(4)).toBe(2)
            expect(Math.sqrt(144)).toBe(12)
            expect(Math.sqrt(2)).toBe(Math.SQRT2)
          })
        });
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed failure
      description: A concise description of what error you're experiencing.
      placeholder: |
        eg: The vitest-codemod script returned the following error:
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected output
      description: The output file you expected to see.
      placeholder: |
        ```ts
        import { expect, describe, test } from 'vitest'

        describe('Math', () => {
          test('.sqrt()', () => {
            expect(Math.sqrt(4)).toBe(2)
            expect(Math.sqrt(144)).toBe(12)
            expect(Math.sqrt(2)).toBe(Math.SQRT2)
          })
        });
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      render: shell
      description: |
        Run `vitest-codemod --version` and paste the result into the form
      placeholder: |
        vitest-codemod: 0.1.0
        - jscodeshift: 0.14.0
        - recast: 0.21.5
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. Or a screenshot if applicable.
