name: Feature Request (transform)
description: Feature request specific to a particular transform (like `jest`)
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: checkboxes
    id: selfservice
    attributes:
      label: Self-service
      description: "Adding features is a great way to give back to open-source projects, and we're more than happy to answer questions and provide context."
      options:
        - label: "I'd be willing to implement this feature"

  - type: dropdown
    id: template-name
    attributes:
      label: Template name
      description: Which template are you adding this feature request for?
      options:
        - jest
        - N/A (described above)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Input code
      description: |
        Provide a minimal code for which you need transformation to be supported.
      placeholder: |
        ```ts
        describe('Math', () => {
          test('.sqrt()', () => {
            expect(Math.sqrt(4)).toBe(2)
            expect(Math.sqrt(144)).toBe(12)
            expect(Math.sqrt(2)).toBe(Math.SQRT2)
          })
        });
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Output
      description: The expected transformed output for the provided code snippet.
      placeholder: |
        ```ts
        import { expect, describe, test } from 'vitest'

        describe('Math', () => {
          test('.sqrt()', () => {
            expect(Math.sqrt(4)).toBe(2)
            expect(Math.sqrt(144)).toBe(12)
            expect(Math.sqrt(2)).toBe(Math.SQRT2)
          })
        });
        ```

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. Or a screenshot if applicable.
